name: billyContinuous

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: billyprojectbucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    #Jar 파일  복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      
    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    # script files 복사
    - name: Copy script
      run: cp ./*.sh ./deploy
    
    - name: Make zip file
      run: zip -r ./billy.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2


    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./billy.zip s3://$S3_BUCKET_NAME/
      
    - name: Code Deploy
      run: aws deploy create-deployment
       --application-name billy
       —deployment-config-name CodeDeployDefault.AllAtOnce
       —deployment-group-name billy-group
       —s3-location bucket=billyprojectbucket,bundleType=zip,key=billy.zip
